language: go
go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
install:
  - go get github.com/stretchr/testify
  - go get github.com/tus/tusd
  - go get github.com/syndtr/goleveldb/leveldb
script: go test -v ./...
notifications:
  email:
    recipients:
      - devs@eventials.com
    on_success: never
    on_failure: always
